sudo: false

language: php

dist: trusty

php:
  - 7.1

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer install -n ; fi

#notifications:
#  slack: slimphp:0RNzx2JuhkAqIf0MXcUZ0asT
